version: 0.2
phases:
  install:
    commands:
      - ./gradlew tasks
  pre_build:
    commands:
      - ./gradlew dependencies
  build:
    commands:
      - ./gradlew clean test jacocoTestReport
  post_build:
    commands:
      - ./gradlew jar
reports:
  unit-coverage:
    files:
      - build/reports/jacoco/test/jacocoTestReport.xml
    file-format: JACOCOXML
  unit-test:
    files:
      - build/test-results/test/*.xml
    file-format: JUNITXML
artifacts:
  files:
    - build/libs/*.jar
cache:
  paths:
    - .gradle/*
    - ~/.gradle/*