version: 0.2
phases:
  install:
    commands:
      - ./gradlew tasks
  pre_build:
    commands:
      - ./gradlew dependencies
  build:
    commands:
      - ./gradlew clean test jacocoTestReport
  post_build:
    commands:
      - ./gradlew jar
reports:
  unit-report:
    files:
      - build/reports/jacoco/test/jacocreportsoTestReport.xml
    file-format: JACOCOXML
artifacts:
  files:
    - build/libs/*.jar