version: 0.2
phases:
  install:
    commands:
      - ./gradlew tasks
  pre_build:
    commands:
      - ./gradlew install
  build:
    commands:
      - ./gradlew clean test jacocoTestReport jar
reports:
  unit-test-result:
    files:
      - build/reports/jacoco/test/jacocreportsoTestReport.xml
artifacts:
  files:
    - build/libs/*.jar